### ISSUE TITLE
Dynamic Texture Uploads (Maybe only P8) Nuke FPS

### ISSUE THREAD

**Issue by SeriousBuggie** [metallicafan212/ICBINDx11Drv#6]
Reproduce:
1. Start UT99.
2. Load map DM-AracaneTemple.
3. Activate Tools -> TimeDemo in game menu.
4. Goes on top above water fall.

Expected result: FPS same as on level (near 60 for me).
Actual result: FPS drop down twice (near 25-30 for me)

![scr_1688527667](https://github.com/metallicafan212/ICBINDx11Drv/assets/70026933/9d73dd2b-67a9-44be-acc5-cce9896dadc3)

**Comment by metallicafan212** [comment]
This should be mostly solved now, I'm still addressing the lack of UpdateTextureRect support.
