### ISSUE TITLE
Win7 not allow use DXGI_FORMAT_B8G8R8A8_UNORM texture format

### ISSUE THREAD

**Issue by SeriousBuggie** [metallicafan212/ICBINDx11Drv#7]
`D3D11 ERROR: ID3D11Device::CreateTexture2D: The format (0x57, B8G8R8A8_UNORM) cannot be bound as an UnorderedAccessView, or cast to a format that could be bound as an UnorderedAccessView.  Therefore this format does not support D3D11_BIND_UNORDERED_ACCESS. [ STATE_CREATION ERROR #92: CREATETEXTURE2D_UNSUPPORTEDFORMAT]`

I make awful dirty fix:
`#define DXGI_FORMAT_B8G8R8A8_UNORM DXGI_FORMAT_R8G8B8A8_UNORM`
Just for make ability run it.

**Comment by metallicafan212** [comment]
I added detection based on the feature level, to use RGBA8 instead of BGRA. A separate issue should be opened for the lightmap issues
