### ISSUE TITLE
Win7 not allow use D3D11_CPU_ACCESS_WRITE CPUAccessFlags

### ISSUE THREAD

**Issue by SeriousBuggie** [metallicafan212/ICBINDx11Drv#8]
`D3D11 ERROR: ID3D11Device::CreateTexture2D: A D3D11_USAGE_DEFAULT Resource cannot have any CPUAccessFlags set. The following CPUAccessFlags bits cannot be set in this case: D3D11_CPU_ACCESS_READ (0), D3D11_CPU_ACCESS_WRITE (1). [ STATE_CREATION ERROR #98: CREATETEXTURE2D_INVALIDCPUACCESSFLAGS]`

In few cases i replace `D3D11_CPU_ACCESS_WRITE` into `0`, for make it work.

**Comment by metallicafan212** [comment]
I removed these flags
