### ISSUE TITLE
Win7 (and some hardware?) not allow use DXT textures with size less from 4

### ISSUE THREAD

**Issue by SeriousBuggie** [metallicafan212/ICBINDx11Drv#9]
`D3D11 ERROR: ID3D11Device::CreateTexture2D: A Texture2D created with the following Format (0x48, BC1_UNORM_SRGB) experiences aligment restrictions on the dimensions of the Resource. The dimensions, which are (Width: 128, Height: 1), must be multiples of (Width: 4, Height: 4). [ STATE_CREATION ERROR #101: CREATETEXTURE2D_INVALIDDIMENSIONS]`

I use dirty fix:
```c++
		Desc.Width				= Max(4, Info.USize);
		Desc.Height				= Max(4, Info.VSize);
```
For ensure it not goes below 4.

**Comment by metallicafan212** [comment]
This is now clamped on texture upload. Closing unless it pops up again
